- name: Update apt cache
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600 # -- checks if cache is older than 1 hour; if so, runs update.

- name: Upgrade all apt packages
  apt:
    upgrade: dist